name: Publish

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build & publish
      run: |
        docker login -u hangox -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        docker build -t hangox/caddy-dnspod:latest .
        docker push hangox/caddy-dnspod:latest
